
[general]
	"Max Distance" = 10
	"Render with Interface Disabled (F1)" = false
	"Height Above Mob" = 0.5
	"Draw Background" = true
	"Background Padding" = 2
	"Background Height" = 6
	"Health Bar Height" = 4
	"Plate Size" = 25
	"Plate Size (Boss)" = 50
	"Show Attributes" = true
	"Show Armor" = true
	"Group Armor (condense 5 iron icons into 1 diamond icon)" = true
	"Color Health Bar by Type (instead of health percentage)" = true
	"HP Text Height" = 14
	"Show Max HP" = true
	"Show Current HP" = true
	"Show HP Percentage" = true
	"Display on Players" = true
	"Display on Bosses" = true
	"Only show the health bar for the entity looked at" = true
	"Show entities with full health" = true
	"Show Debug Info with F3" = true
	#Blacklist uses entity IDs, not their display names. Use F3 to see them in the Neat bar.
	Blacklist = ["minecraft:shulker", "minecraft:armor_stand", "minecraft:cod", "minecraft:salmon", "minecraft:pufferfish", "minecraft:tropical_fish", "supplementaries:firefly", "artifacts:mimic", "alexsmobs:fly", "alexsmobs:flying_fish", "alexsmobs:blobfish", "alexsmobs:devils_hole_pupfish", "alexsmobs:hummingbird", "alexsmobs:crow", "alexsmobs:seagull", "alexsmobs:centipede_body", "alexsmobs:centipede_tail", "alexsmobs:leafcutter_ant", "blue_skies:firefly", "ars_nouveau:whirlisprig", "aquaculture:arapaima", "aquaculture:arrau_turtle", "aquaculture:atlantic_cod", "aquaculture:atlantic_halibut", "aquaculture:atlantic_herring", "aquaculture:bayad", "aquaculture:blackfish", "aquaculture:bluegill", "aquaculture:boulti", "aquaculture:box_turtle", "aquaculture:brown_shrooma", "aquaculture:brown_trout", "aquaculture:capitaine", "aquaculture:carp", "aquaculture:catfish", "aquaculture:gar", "aquaculture:jellyfish", "aquaculture:minnow", "aquaculture:muskellunge", "aquaculture:pacific_halibut", "aquaculture:perch", "aquaculture:pink_salmon", "aquaculture:piranha", "aquaculture:pollock", "aquaculture:rainbow_trout", "aquaculture:red_grouper", "aquaculture:red_shrooma", "aquaculture:smallmouth_bass", "aquaculture:starshell_turtle", "aquaculture:synodontis", "aquaculture:tambaqui", "aquaculture:tuna"]

